# Generated by Django 4.2.2 on 2023-08-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeRPGappMain', '0003_profile_rpg_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
