# Generated by Django 4.2.2 on 2023-08-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeRPGappMain', '0004_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='markComplete_1',
            field=models.IntegerField(default=0),
        ),
    ]
