# Generated by Django 4.2.2 on 2023-08-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeRPGappMain', '0005_profile_markcomplete_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='markComplete_1',
            field=models.BooleanField(default=False),
        ),
    ]
