# Generated by Django 4.2.2 on 2023-09-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeRPGappMain', '0006_alter_profile_markcomplete_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='CodeRPGappMain.skill'),
        ),
    ]
